export bound from './bound'
export callIfExists from './callIfExists'
export reduceProps, {selectProps} from './reduceProps'
export toKebabCase, {toKebabCaseTrimmed, kebabRe} from './toKebabCase'
export requestAnimationFrame, {
  cancelAnimationFrame
} from './requestAnimationFrame'
export requestTimeout, {clearRequestTimeout} from './requestTimeout'
export requestInterval, {clearRequestInterval} from './requestInterval'
export loadImages, {loadImage} from './loadImages'
export withContextFrom from './withContextFrom'
export getComputedStyle from './getComputedStyle'
export getUniqueID from './getUniqueID'
export debounce from './debounce'
export throttle from './throttle'
export compose from './compose'
export perf from './perf'
export createOptimized from './createOptimized'
export * as namespace from './namespace'
